version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    labels:
      - 'type: dependencies'
      - 'status: safe to test'
    commit-message:
      prefix: 'chore'

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    labels:
      - 'type: dependencies'
      - 'status: safe to test'
    commit-message:
      prefix: 'chore'
