version: 2
updates:

  # Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  open-pull-requests-limit: 20
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
  labels:
    - "type: dependencies"

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  open-pull-requests-limit: 20
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
  labels:
    - "type: dependencies"
