# Use docker image with postgres support: https://www.gitpod.io/docs/config-docker
image: gitpod/workspace-postgres

# Start up tasks: https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    init: yarn install
    command: |
      yarn prisma:migrate:dev
      yarn prisma:seed
      yarn docker:redis
      gp sync-done setup
      yarn generate:watch
    env:
      DATABASE_URL: postgresql://gitpod@localhost/jabrefonline
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev
    env:
      DATABASE_URL: postgresql://gitpod@localhost/jabrefonline
  - name: Prisma Studio
    init: gp sync-await setup
    command: yarn prisma:studio
    env:
      DATABASE_URL: postgresql://gitpod@localhost/jabrefonline

# Expose ports: https://www.gitpod.io/docs/config-ports/
ports:
  # Redis
  - port: 6380
    onOpen: ignore
  # Database
  - port: 5432
    onOpen: ignore
  # Dev server
  - port: 3000
    onOpen: open-preview
  # Prisma Studio
  - port: 5555
    onOpen: open-preview
