name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

      - name: Check types
        run: pnpm typecheck

      - name: Validate GraphQL operations
        run: pnpm validate

  test:
    name: Build & Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jabref
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to port 6380 on host
          - 6380:6379

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/jabref?schema=public
      SHADOW_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/jabref_shadow
      SESSION_PASSWORD: somerandompasswordNxFHaqCSPpBe6n5kRz2dru4hJ7K9bjgEtmsV8QAT3MDXcUfWGL

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Init database
        run: pnpm prisma:push
        env:
          NUXT_DATABASE_URL: ${{ env.DATABASE_URL }}

      # Check that no schema changes have been done without corresponding migration files have been added
      - name: Create shadow database for schema drift detection
        run: PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE jabref_shadow;"

      - name: Detect database schema drift
        run: pnpm prisma:migrate:diff
        env:
          NUXT_DATABASE_URL: ${{ env.DATABASE_URL }}
          NUXT_SHADOW_DATABASE_URL: ${{ env.SHADOW_DATABASE_URL }}

      - name: Build
        run: pnpm build
        env:
          NUXT_SESSION_PASSWORD: ${{ env.SESSION_PASSWORD }} # Needed for prerending

      - name: Start server
        run: pnpm start &
        env:
          NUXT_GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUXT_SESSION_PASSWORD: ${{ env.SESSION_PASSWORD }}
          NUXT_DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Run tests
        run: pnpm run test --coverage
        env:
          TEST_URL: http://localhost:3000
          NUXT_DATABASE_URL: ${{ env.DATABASE_URL }} # To seed the database
          # The tests need these tokens to run, but their actual value should not matter
          NUXT_GITHUB_REPO_TOKEN: 'SIGNAL_TO_RUN_TEST'

      - name: Build Storybook
        if: always()
        run: pnpm storybook:build

      - name: Publish and test Storybook
        if: always()
        uses: chromaui/action@eea1606238fd97a70b5af723d103953d1f40967b # v15.3.1
        with:
          projectToken: 'b3787adf2fa5'
          # Don't wait until Chroma verified the build (for this we have the Github check)
          exitOnceUploaded: true
          storybookBuildDir: storybook-static
          debug: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
